import { MigrationInterface, QueryRunner } from "typeorm";

export class AddCalendarParticipantEntity1712873227195 implements MigrationInterface {
	name = "AddCalendarParticipantEntity1712873227195";

	public async up(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(
			`--sql
      CREATE TYPE "public"."participant_role" AS ENUM (
        'member',
        'admin',
        'owner'
      )`
		);

		await queryRunner.query(
			`--sql
      CREATE TABLE "calendar_participant" (
        "id"          integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "calendar_id" integer NOT NULL,
        "user_id"     integer NOT NULL,
        "role"        "public"."participant_role" NOT NULL DEFAULT 'member',
        "favorite"    boolean NOT NULL DEFAULT false,

        CONSTRAINT "PK_d8a7b7ee7102bed683fe1a77ab5" PRIMARY KEY ("id"),
        CONSTRAINT "FK_5841ce36560df8796e52a89ddff" FOREIGN KEY ("calendar_id")
          REFERENCES "calendar"("id") ON DELETE CASCADE ON UPDATE NO ACTION,
        CONSTRAINT "FK_bc9bd2eae7751e7f6ba1e1e165e" FOREIGN KEY ("user_id")
          REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION
      )`
		);
	}

	public async down(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(`DROP TABLE "calendar_participant"`);
		await queryRunner.query(`DROP TYPE "public"."participant_role"`);
	}
}
