import { MigrationInterface, QueryRunner } from "typeorm";

export class AddCalendarEntity1712873227194 implements MigrationInterface {
	name = "AddCalendarEntity1712873227194";

	public async up(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(
			`--sql
      CREATE TABLE "calendar" (
        "id"        integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
				"google_id" text,
        "owner_id"  integer NOT NULL,
        "summary"   text NOT NULL,
				"favorite"  boolean NOT NULL DEFAULT false,

        CONSTRAINT "PK_2492fb846a48ea16d53864e3267" PRIMARY KEY ("id"),
        CONSTRAINT "FK_5092d114b68a70982b83504475f" FOREIGN KEY ("owner_id")
          REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION
      )`
		);
	}

	public async down(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(`DROP TABLE "calendar"`);
	}
}
