import { MigrationInterface, QueryRunner } from "typeorm";

export class AddEventPeriodEntity1712873227197 implements MigrationInterface {
	name = "AddEventPeriodEntity1712873227197";

	public async up(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(
			`--sql
      CREATE TABLE "event_period" (
        "id"              integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "event_id"        uuid NOT NULL,
        "start_date"      date,
        "start_date_time" TIMESTAMP WITH TIME ZONE,
        "start_timezone"  text,
        "end_date"        date,
        "end_date_time"   TIMESTAMP WITH TIME ZONE,
        "end_timezone"    text,

        CONSTRAINT "PK_798be5d81388e4c9b675c877ddd" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_8726fd86c5cb5d5966e3108f83d" UNIQUE ("event_id"),
        CONSTRAINT "FK_8726fd86c5cb5d5966e3108f83d" FOREIGN KEY ("event_id")
          REFERENCES "event"("id") ON DELETE CASCADE ON UPDATE NO ACTION
      )`
		);
	}

	public async down(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(`DROP TABLE "event_period"`);
	}
}
