import { MigrationInterface, QueryRunner } from "typeorm";

export class AddUserEntity1712873227193 implements MigrationInterface {
	name = "AddUserEntity1712873227193";

	public async up(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(
			`--sql
      CREATE TABLE "user" (
        "id"                         integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "google_id"                  text,
        "google_api_refresh_token"   text,
        "google_calendar_sync_token" text,
        "email"                      text NOT NULL,
        "password"                   text,
        "name"                       text NOT NULL,
        "picture"                    text,
        "created"                    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

        CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"),
        CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")
      )`
		);
	}

	public async down(queryRunner: QueryRunner): Promise<void> {
		await queryRunner.query(`DROP TABLE "user"`);
	}
}
