version: "3.2"
services:
  postgres:
    image: postgres:15.2
    container_name: calendar-postgres
    hostname: postgres

    env_file: .env

    ports:
      - 5432:5432

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}

    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database_network

    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    container_name: calendar-pgadmin4

    logging:
      driver: none

    env_file: .env

    ports:
      - "5050:80"

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
      GUNICORN_ACCESS_LOGFILE: /dev/null

    depends_on:
      - postgres
    networks:
      - database_network

    restart: on-failure

  backend:
    image: calendar-backend
    container_name: calendar-backend

    build:
      context: .
      target: development

    volumes:
      - ./src:/usr/src/app/src

    env_file: .env

    ports:
      - ${PORT}:${PORT}

    depends_on:
      - postgres
      - redis

    networks:
      - database_network

    restart: on-failure

  redis:
    image: redis:7.2-alpine
    container_name: calendar-redis
    hostname: redis

    command: redis-server --save 20 1 --loglevel warning

    ports:
      - 6379:6379

    volumes:
      - redis-data:/data

    networks:
      - database_network

volumes:
  postgres_data:

  redis-data:

networks:
  database_network:
    driver: bridge
